{% set name = "flufl.enum" %}
{% set version = "5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c294d7f078ee6217bde505505d67a2a2a0fec9a5386a5f57013e247669d087c5

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - flufl
    - flufl.enum
    - flufl.enum.docs
    - flufl.enum.tests

about:
  home: http://launchpad.net/flufl.enum
  license: LGPLv3+
  license_file: LICENSE
  summary: A Python enumeration package.

extra:
  recipe-maintainers:
    - cehbrecht
