{% set name = "flufl.enum" %}
{% set version = "4.1.1" %}
{% set sha256 = "67edefaca4347663c95f370398edce1d2267f293f25addca5680bd8bdc51a51c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - setuptools
  host:
    - pip
  run:
    - python

test:
  imports:
    - flufl
    - flufl.enum
    - flufl.enum.docs
    - flufl.enum.tests

about:
  home: http://launchpad.net/flufl.enum
  license: LGPLv3+
  summary: 'A Python enumeration package.'

extra:
  recipe-maintainers:
    - cehbrecht
