# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HlcxboVsJi0ntIlgeOC7V+8HgHnzEWLJjXkcqUjAbMNDZW0/rgIYcfoj5Xu4iPPsNqph5RDGQSgY4QNwfXiSON5iD/45+/TaGhpK9b6S2ZwzNUH1joOz8Lp9N5ba1NQqjy3ccicqzvJ7II/flWBrMFlXft32/ElASLTr1+to7TEaDoIiLYDxLU0l/YfZH3eCCVIh8OAzEGcblO7zXiFeCLKJ6D3vRJ5yKWh+myfL4v4Sks6yY1hGoBGpCUnFX3O0Yo3DvbbmnAEkxDWQpDq343i8EpIKqafZ+7ziX5aZayN7LDC4htyXgz51zHKDiW4IwMgulPimn3OUBojVuECusFjfwbQGpv+V2L+X+Be4czg7RkQ4AB2rgbEUAjrddj1W1lgEzrns1T3Iq+2I/+KsqZ40XhG8aPSSaL74wULXMB8OSkRB1aBHVroP2dpfXlwE7ZZbJDjMecr5qeyf8bdx3QNBVvD5YsHTSki/JU/VWtLT1+Y6+pFbNxa4iuF8uRYSGzccwX2JT2QUdhsJd76xRUXdoJrf2JuZVXlgaKWuFdIolAgZtuBxgor3bR/2S+solbOSdCdOCwbJV3H9WTzH/iSGKJEVMOu++VcB7dI4jZ5/LxlUSvjt239Tfb1w6vlvtFrE/W64Th72uOYKT7+WV8F8fiCXZBWhDjRDNtw5+js="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
