travis:
  secure:
    BINSTAR_TOKEN: LPq1ESroGiZ2AlQizr7ib3SiGAKAiQAK0/Lnqn7YGHSBXGm9Yupe7hoe7yHZvqI3QR8wXP2+hvNVFsqG8m84gwZvQijb0Mda8vPDTejJqdLTf9ICATLDd7Ay31aAvTdzVkkzXOBLX8ADjRXaiRGxfbZzpXbCbMBAaMEoj0g71mPFkHVKsfu4OrslkRhOWjk6ojcmvLHkFZGfouoTWbby9xKAYWZ5rya+19IMr0SdEG7CFWvPfqbdDp8eoYyQe1xr4qJgOrw6hGtkA5Nfobh/oRK/kj1O+J9V6jaNZcf5sgYgsVybpiUY/ha3kFM2KovT0JVZvovQhEuiX7nIEkqZPUTImLd5XRGg8EJuScNVwWFOeDoRmpCePwCQXHWzBk5TCq4B6Vr6TYxtvmzVOVg2vIE71IvIfDitkb2DO1TnUmbDEvivKGu2s7remSrsNpECW2lre6diHlMiJ9w3+8XRVaqBmHgYw6ED3USaE+s0GrO1P8qC3lZMASzIVaib0H8z2gL1UIbMnUoHgp35Ry0HsvglcqphpyOnI4FZ57GYg8O758Znfgc8URDJob8Yej+kIiGiJLyCyYg8GZQd142309mQqp4UgkNgEw8MWDnyt8xBke6Id65q4w2SRWIep2FSmISmTlgqOEw+HFfC/qTgp/ul/DCB96RT/2KBzffg1gk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
