travis:
  secure:
    BINSTAR_TOKEN: rdxznLQh8JCiuNG23FZsfQIz9vWwGkA0uKGYS3eDJl58FPHGRPIfufdvSCKggkOJnyW3a6h2XKrMO9gNdwU2OvgvwHWGn1ZpxFEUxcF+ZCNMye/xZw/2GM2rR6euuPI5/LoilX6SaT/JurSrHFkD3aXzivDbQOOUvUTcVz7nYTmNGFOTKORgLf7fvqaNJ6ipJppvR0QCLMAVFG+40mCPr21Odm49GJ2uKrzGAsGjRvm43d2dr5Q4GVlQsepKSMCDuyTfJHoAhmU7BuP4MpfZ/gnVQI0Lj+mdyOwynEY7W/beKy8x3NRAnOlZ2YaFbvLVN5kztvsT1fpYZWkQvw12WV4xUrEfD63xBvG7iLJJTnfnb5xaVzMmNCbsS6HgGZrT4IRswgYOa6SDeevaRnL73d99FKlM5Ok5jQYUOcWwobo/iOBaBLqR2Ch0NIEEF9+CdEC7ioNjjut7U1KtltINsihHDROmYZ5Hm0PcUdwj2qRw+bBFVGzw6IroSjQqQfBlkFAtPIjRohHWlaR79QaR/jY1TfKls5NxvNiFEae0vTij9u9h/mBhSCMhYglTEXP+aNOljmiMqtQJ0ygH/vcOLKfAwUduzcLDXA1v8aJPpM6AlSSw9tIHp6Ag+OoM1Xegw1eMBwFkRmmcGKfBs9gm5qO6or2FL4t9lNxm+MFBFs4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
